language: node_js
addons:
  chrome: stable
node_js:
- '10'
env:
  global:
  - FTP_USER=unaux_27579723
before_install:
- chmod u+x travis/*
install:
- npm install
script:
- travis/build.sh
- travis/deploy.sh
