language: node_js
addons:
  chrome: stable
node_js:
- '10'
install:
- npm install
script:
- npm run clean && npm run build:prod-with-context
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_SECRET_KEY
  target_branch: gh-pages
  local_dir: dist/
  on:
    branch: try-gh-pages-deploy
branches:
  only:
  - gh-pages
  - /.*/
