language: node_js
node_js:
- "8"
env:
  global:
    - "FTP_USER=greouxlocation"
    - secure: EqK15DgXauNBICipIQcDCJl6IoUWNlEwW8gpludX7guKxsX39NQ95yKszPDx6TkWd9FAOqwNYNQh6zA60t2zLAkhXojLmuXi65bW117/kknyBnPER/dYf58nROrCf1McnFcjo9WZe3nMBUugi01VGUiP7PrupRFIWdw10NrHriZadXJYQH593kWh4iTER7bhx4liPotA8MH0I41XxsbcvK+9coJMUtqxHEDdD6I1f6sGK7XGpfM2jxWMfSmArtPZKQRNEImofkyurQwkysASauq9N4CmJs3oFlDhVscg5W7AmImcfAU+zjwjt/BQqMcguY7MszSqYS39fBLEIuN2PqNbMHfr/y5qeh6xEa/Gx8HX30DBBcXmzAr/z9ovD24CJxTjqDUN+me6WFsB6uFBsFz9BZ1sYHTbGIuFdKNpVVBLSPBl4aO4HUJEoikOLT1WBl6jHQRPryccSqu8WyNft5nAKpNYrljrAM3Vp/fM4npQeLbMo+pXPpWo7DeQMRnyEAiNFycEpP+fJenfnsP7b5lv3eeg3oIaICwUZE6HZMgp1MmMn7HdaxBYkcDMezkyWUKdbomphA0RfHbhpOJpmIEy7O6zELsob5wIfNKLiNhNo5IQnBhs1kjWHRv5McvxigZkMMlN9wqx55lirZWhodYSBek7ZzX7iP2uIP8F/8g=
before_install:
  #- npm i -g npm@3.10.10
  #- npm i -g npm@5.3.0
install:
- npm install
script:
- ls -l travis
- chmod o+x travis/build.sh
- travis/build.sh
after_success:
- cd dist
- mkdir assets/security
- echo "<?php define('BASE_PWD', '$GREOUXLOCATION_FTP_PWD'); ?>" > assets/security/key.php
- find * -type f -exec curl -u $FTP_USER:$GREOUXLOCATION_FTP_PWD --ftp-create-dirs -T {} ftp://ftpperso.free.fr/{} \;
- cd ..
after_script:
- set -xe
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
- echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
- apt-get update -yqqq
- apt-get install -y google-chrome-stable
- npm install -g protractor
- webdriver-manager update
- webdriver-manager start &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
- npm run deploy:check
