language: node_js
addons:
  chrome: stable
node_js:
- '10'
env:
  global:
  - FTP_USER=unaux_27579723
  - secure: A5rtObvZM6weKySWybZunFfy3f0u8ShljN4EKg138qIBOsOYakDXkut5sBIRXxtdenqIik0DfBCw1qRcOCjAW5ol7F9Wu2SEJvL7811Eud50Gteiv5as1wQNl9v9db+agM0xZpIrZfXvQaodObQOAyD6x3kaTjKjVOfbTuiXGAjHaqpbfipirdP8TpKsPkrjvs5IKWEowmQoO0t6NvcB5YhLlUvz4Mz6af8RzZFMNDP90iBzQw8GivBYMUt0Y2mNsk8eMeJMkhqauLMAjJki48R9zDB3QxPMtMC3XdtSg293FMef8/CAr2wKa6vi/mpoYIhJ9qpvPCHZsyatm/h0alt8Mhk1B5NZbSyRPpgyrmmX4RSyfJTAb7Yy4QvUQa+JcVFfg5GjK/Bq/Azui2dhm/jSoAe/OHyuHDuHtn8syNpZJj9jwTZPiBMfuxndyhfeJ2QCUbF8in65G8sBESGxfQ4DP3/AcRDigfRp3WZcsz5szP5gxuVSdaTDHs/ikDmtcZd6OwKnjA15Z9zGkcKZgdwO9p6/VMqi58Cp1wHfWdi0Zj4gN+s+iNM9iVyLizugjt1b70ie1pEARWtnCSXTdzVoDur2p/uFBD4oGljsLOAtA1npOzk2/G8SPuUiKfMFsLMVC+G+6coClS/oinbAaHBfA0jsB9NWT0PvngDFucg=
before_install:
- chmod u+x travis/*
install:
- npm install
script:
- travis/build.sh
- travis/deploy.sh
